version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:15"
      timezone: "UTC"
    open-pull-requests-limit: 5
